### ISSUE TITLE
NIHMS harvester failing to get data from website

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/general-issues#122]
I am getting this when running the harvester.  This should have nothing to do with the changes made in the index.

```
###!!! [Parent][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

java.lang.RuntimeException: An error occurred while downloading the NIHMS files.
       at org.dataconservancy.pass.loader.nihms.NihmsHarvester.harvest(NihmsHarvester.java:232)
       at org.dataconservancy.pass.loader.nihms.cli.NihmsHarvesterApp.run(NihmsHarvesterApp.java:105)
       at org.dataconservancy.pass.loader.nihms.cli.NihmsHarvesterCLI.main(NihmsHarvesterCLI.java:85)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: //a[starts-with(@href, 'https://www.ncbi.nlm.nih.gov/pmc/utils/pacm/c?')]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'msel-passjobs', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.2.3.el7.x86_64', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: true, moz:processID: 14570, moz:profile: /tmp/rust_mozprofile.hmtM2A..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-862.2.3.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 966b8686-7598-4996-8726-84f1bcf7b204
*** Element info: {Using=xpath, value=//a[starts-with(@href, 'https://www.ncbi.nlm.nih.gov/pmc/utils/pacm/c?')]}
       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
       at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
       at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
       at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
       at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
       at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
       at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
       at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:421)
       at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
       at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
       at org.dataconservancy.pass.loader.nihms.NihmsHarvester.harvest(NihmsHarvester.java:199)
       ... 2 more
An error occurred while downloading the NIHMS files.

```

**Comment by karenhanson** [comment]
We determined that the password expires periodically. This error went away once the password was renewed.
